### ISSUE TITLE
GIF doesn't generate

### ISSUE THREAD

**Issue by Papayalux** [Scheliux/mpv-gif-generator#9]
Similar to #1, except mpv has already been added to my path, and I can already access it from Command Prompt.
Upon pressing ctrl+g to generate the gif, a blank command prompt window opens for a few seconds before closing. Mpv then says the gif was generated, yet it doesn't appear in the video's directory or in C:/Program Files/mpv/gifs.

**Comment by mortang2410** [comment]
I can confirm that there is no gif generated. There aren't enough messages to figure out what went wrong.
